### PR TITLE
Capstone Proposal

### PR DESCRIPTION
**Pull request by iTaylorCodes**
Created the proposal for Capstone-1: Gamr.
Includes: 
- API description and endpoint
- Application guidelines
- Database schema design
- Potential routes

### CODE REVIEW

**Comment by alexkayabula** [comment]
@iTaylorCodes Please add a label `ready for review`. Use this for reference [Link](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels). You can as well create other labels like `fix`.

**Review by alexkayabula — CHANGES_REQUESTED** [review]
Please make the changes above so that we merge.

**Comment by alexkayabula** [comment]
Remember!! you do not have to close a pull request in order to make changes.

**Review by alexkayabula — CHANGES_REQUESTED** [review]
Please change the file extensions from `.txt` to `.md`

**Comment by iTaylorCodes** [comment]
I was able to push my amended commit using a force push

**Review by alexkayabula — APPROVED** [review]
LGTM

**Pull request merged**
