### PR TITLE
Setup CI/CD pipeline

### LINKED ISSUE #10: [2]Setup Continuous Integration and Continuous Development(CI/CD)
In order for our team to build a robust application, we will need to test all the functionality and ensure that the application is void of bugs and working as expected.

You are tasked with implementing CI/CD pipeline to ensure that we automate the software delivery process. I recommend [Travis CI](https://travis-ci.org/).

**What is a CI/CD pipeline?**
A CI/CD pipeline automates your software delivery process. The pipeline builds code, runs tests (CI), and safely deploys a new version of the application (CD). Automated pipelines remove manual errors, provide standardized feedback loops to developers, and enable fast product iterations.

Below are a few resources that can help you learn more about the CI/CD

**CI/CD Continuous Integration and Continous Development**
[
https://www.youtube.com/watch?v=l-wdLGYwlVc](
https://www.youtube.com/watch?v=l-wdLGYwlVc)
[https://www.youtube.com/watch?v=l-wdLGYwlVc)](https://www.youtube.com/watch?v=_WvjhrZR01U)

Remember to add a build status badge.
https://docs.travis-ci.com/user/status-images/

Kindly raise a pull request for this task.

### PR DESCRIPTION
**Pull request by iTaylorCodes**
### What does this PR do?
- This Pull Request integrates a CI/CD pipeline using Travis CI
- This PR closes #10 
### Description of Task to be completed
- Created .travis.yml file to control CI/CD pipeline. Whenever new code is pushed to repository, Travis CI will test the build and notify if tests fail.
### How should this be manually tested?
- Push new build to Github, open Travis CI and choose the correct repository. Click "Restart build" and it will run all tests.

### CODE REVIEW

**Review by alexkayabula — CHANGES_REQUESTED** [review]
@iTaylorCodes the build is failing. Please fix the build.

**Comment by alexkayabula** [comment]
@iTaylorCodes you can use this as a reference 
https://docs.travis-ci.com/user/languages/python/

**Comment by iTaylorCodes** [comment]
@alexkayabula The .travis.yml file was reading the language as Ruby. After refactoring the .travis.yml file it now reads Python, the correct language, and is no longer failing. 👍

**Review by alexkayabula — CHANGES_REQUESTED** [review]
@iTaylorCodes please add the badge.

**Comment by iTaylorCodes** [comment]
While getting the badge incorporated, build started failing again. Working on getting the build to pass.

**Comment by alexkayabula** [comment]
@iTaylorCodes please add a badge and we get this merged.

**Comment by alexkayabula** [comment]
@iTaylorCodes look into the changes I made. Re-request review if all is good.

**Review by alexkayabula — APPROVED** [review]
LGTM

**Pull request merged**
