### PR TITLE
Implement User Login and Logout

### LINKED ISSUE #19: [9] Users should be able to login/logout
Create user login page. This should include /login and /logout views and users/login template.

**Make sure to add tests for /signup, /login, and /logout views.**

### PR DESCRIPTION
**Pull request by iTaylorCodes**
### What does this PR do?
- This Pull Request sets up the user login and logout feature
- This PR closes #19 
### Description of Task to be completed
- Setup /login and /logout views. Setup users/login template. Add styles to login page. Create tests for both views.
### How should this be manually tested?
- Visit /login, fill out login form, then visit any other page and verify the navbar has updated to show a logged in user and a welcome message is flashed. Then visit /logout to logout.

https://user-images.githubusercontent.com/76837421/130552750-5e682aba-844c-46fa-82ff-1f434c41c4e5.mov

### CODE REVIEW

**Review by alexkayabula — CHANGES_REQUESTED** [review]
Fix dropped test coverage.

**Comment by alexkayabula** [comment]
@iTaylorCodes what happens when a user logins in successfully? In the video, I have noticed that you are redirecting to the signup page and no pages are rendered except `302`. This does not seem right. Below are my suggestions.

1. On successful `sign up`, a user should be redirected to the `login page`. (Work on this [issue](https://github.com/iTaylorCodes/Capstone-1/issues/29) first, it is a priority. Create a ``separate`` Fix PR for it).
2. On successful `login`, a user should be redirected to the `/`, homepage or some other page depending on the application design. (Fix this in this PR).
3. On successful `logout`, a user should be redirected to the login page. (Fix this in this PR).
4. Upload a new video with the suggested changes made.

Thank you.

**Comment by iTaylorCodes** [comment]
@alexkayabula When a user signs up, I want them to be redirected to the add user's favorites page, which we decided to setup after we complete the basic `signup`, `login`/`logout`, `edit profile`, and `delete account` features.

On successful `login` the user is redirected to `/` which will be the homepage, to be set up in #22 

On successful `logout` the user is redirected to `/login`

The confusion might be from the Debug Toolbar intercepting redirects. I made another video without intercepting redirects.

**Comment by iTaylorCodes** [comment]
@alexkayabula The dropped test coverage comes from these 2 lines. I have not been able to find how to cover g.user, and flask session in a test. What would you recommend?
Screen Shot 2021-08-22 at 11 24 40 PM

**Comment by alexkayabula** [comment]
> @alexkayabula When a user signs up, I want them to be redirected to the add user's favourites page, which we decided to set up after we complete the basic `signup`, `login`/`logout`, `edit profile`, and `delete account` features.
> 
> On successful `login` the user is redirected to `/` which will be the homepage, to be set up in #22
> 
> On successful `logout` the user is redirected to `/login`
> 
> The confusion might be from the Debug Toolbar intercepting redirects. I made another video without intercepting redirects.

1. I recommend that when a user signs up they are redirected to the login page because a user redirecting to the user's favourites page without logging in beats the purpose of the `authorization` to the app. Access to the user's favourites page should be through logging in to the app. I believe it is a better approach.

**Comment by alexkayabula** [comment]
When accessing the signup page, why is the notification/message  ```Hello, testfirstname!``` displayed? If a signed user accesses the signup page, that notification should not be displayed. If you need to display that notification/message, it can be placed in the nav bar.

**Comment by alexkayabula** [comment]
> @alexkayabula The dropped test coverage comes from these 2 lines. I have not been able to find how to cover g.user, and flask session in a test. What would you recommend?
> Screen Shot 2021-08-22 at 11 24 40 PM

Kindly write the respective tests for those lines.
1. For line `47`, try checking that the `CURRENT USER KEY` does not exist in the session after deleting.
2. For line `30`, try checking that the logged-in user session contains a specific  `CURRENT USER KEY`.

**Review by alexkayabula — CHANGES_REQUESTED** [review]
Check out the comments and make the necessary changes. Please add a video.

**Comment by iTaylorCodes** [comment]
I added the tests on lines 91 and 101 to test for `CURRENT USER KEY` in the session or not, but it still isn't being covered in coveralls.

Screen Shot 2021-08-23 at 8 23 34 PM

**Comment by iTaylorCodes** [comment]
@alexkayabula I have updated the video walkthrough using a temporary homepage to show how `/login` redirects.

**Comment by alexkayabula** [comment]
> I added the tests on lines 91 and 101 to test for `CURRENT USER KEY` in the session or not, but it still isn't being covered in coveralls.
> 
> Screen Shot 2021-08-23 at 8 23 34 PM

You had to restart the build for the tests to pass. Due to caching sometimes the changes may take time to take effect.
Confrim that everything is working and request for a review so that we merge.

**Review by alexkayabula — CHANGES_REQUESTED** [review]
Change the title of the PR to `Implement User Login and Logout`

**Review by alexkayabula — APPROVED** [review]
LGTM

**Pull request merged**
