### PR TITLE
User should be able to edit their profile.

### LINKED ISSUE #20: [11] Users should be able to edit their profiles
Create form to edit user profile and edit user favorites. Should include /users/<user_id>/edit view and users/edit template.

### PR DESCRIPTION
**Pull request by iTaylorCodes**
### What does this PR do?
- This Pull Request implements the feature for a user to edit their profile.
- This PR closes #20 
### Description of Task to be completed
- User should be able to edit their profile, including their favorites.
### How should this be manually tested?
- From the user's profile, click "Edit Profile". Then change any profile values. Click "Save" and verify changes were made to user's profile.

https://user-images.githubusercontent.com/76837421/131184939-b0946373-13cf-4a3d-af8c-2591f2c256eb.mov

### CODE REVIEW

**Comment by iTaylorCodes** [comment]
Still setting up tests for this PR.

**Comment by iTaylorCodes** [comment]
Travis CI service is down. Currently unable to check code coverage so reaching out to Travis CI for support.

**Comment by iTaylorCodes** [comment]
@alexkayabula This PR was a pretty big task, it set up API usage to get the list of games for a user to add to their profile.

**Comment by alexkayabula** [comment]
> @alexkayabula This PR was a pretty big task, it set up API usage to get the list of games for a user to add to their profile.

I believe the reason is that a lot of the implementation in this PR should have been implemented in different PRs. 
This PR should be `strictly` for allowing `editing` of the User profile page.

Move the `set up API usage to get the list of games for a user to add to their profile` and other unrelated parts of this PR into different PRs namely;
1.  "Users should be able to access a list of games in their profiles page"
2.  "Users should be able to add favourite games in their profiles page"

Just like we discussed in our previous call, it is important to have each PR implementing a specific and unique feature.

Kindly let me know if you have reservations in regards to this but otherwise, we shall need to implement the changes above.

**Review by alexkayabula — CHANGES_REQUESTED** [review]
Kindly reply to the comments on this PR.

**Comment by iTaylorCodes** [comment]
> > @alexkayabula This PR was a pretty big task, it set up API usage to get the list of games for a user to add to their profile.
> 
> I believe the reason is that a lot of the implementation in this PR should have been implemented in different PRs.
> This PR should be `strictly` for allowing `editing` of the User profile page.
> 
> Move the `set up API usage to get the list of games for a user to add to their profile` and other unrelated parts of this PR into different PRs namely;
> 
> 1. "Users should be able to access a list of games in their profiles page"
> 2. "Users should be able to add favourite games in their profiles page"
> 
> Just like we discussed in our previous call, it is important to have each PR implementing a specific and unique feature.
> 
> Kindly let me know if you have reservations in regards to this but otherwise, we shall need to implement the changes above.

I see, that makes sense. I will go ahead and separate this into multiple PRs.

**Comment by iTaylorCodes** [comment]
@alexkayabula Resolved conflicts between the main branch and this branch. Ready for review 😊

**Review by alexkayabula — APPROVED** [review]
LGTM

**Pull request merged**
